title: "Engineering Handbook"
description: "How we work at Holaluz Engineering"
themeConfig:
  logo: "/holaluz.png"
  lastUpdated: true
  sidebar:
    - "/"
    - title: "Organization"
      path: "/organization/"
      children:
        - "/organization/"
        - "/organization/teams"
    - title: "Operative"
      path: "/operative/"
      children:
        - "/operative/"
    - "CONTRIBUTING"
