base: "/handbook/"
title: "Engineering Handbook"
description: "How we work at Holaluz Engineering"
themeConfig:
  logo: "/holaluz.png"
  lastUpdated: true
  sidebar:
    - "/"
    - title: "Organization"
      path: "/organization/"
    - title: "Operative"
      path: "/operative/"
      children:
        - "/operative/"
    - "CONTRIBUTING"
