name: Deploy to Github pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the static website
        run: npx vuepress build
      - name: Deploy pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.HANDBOOK_DEPLOY_TMP_ANGEL }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: .vuepress/dist
